language: node_js
node_js:
  - "stable"
addons:
  firefox: "50.0.2"

env:
  global:
    - DISPLAY=:99.0
    - JPM_FIREFOX_BINARY=/usr/local/bin/firefox

before_install:
  - sh -e /etc/init.d/xvfb start
